name: Build
on: [ push, pull_request ]
jobs:

  # validate gradle wrapper checksum
  gradleValidation:
    name: Gradle Wrapper Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

  # run verifyPlugin and test tasks
  test:
    name: Test
    needs: gradleValidation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Gradle Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Run Linters and Test
        run: ./gradlew check

      #- name: Verify Plugin
      #  run: ./gradlew verifyPlugin
